rules:
  body-empty:
    level: warning
  body-max-length:
    level: warning
    length: 128
  description-empty:
    level: error
  # description-format:
  #  level: error
  #  format: ^[a-z]*$
  description-max-length:
    level: error
    length: 64
  scope:
    level: warning
    options:
      - binary
      - script
      - ci
      - dependencies
      - readme
  scope-empty:
    level: warning
  # scope-format:
  #  level: error
  #  format: ^[a-z]*$
  scope-max-length:
    level: warning
    length: 12
  subject-empty:
    level: error
  type:
    level: error
    options:
      - build
      - chore
      - ci
      - docs
      - feat
      - fix
      - perf
      - refactor
      - revert
      - style
      - test
  type-empty:
    level: error
  # type-format:
  #  level: error
  #  format: ^[a-z].*$
  type-max-length:
    level: error
    length: 8
